spec:
  rules:
  - host: kameronbek.traefik.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-app-service
            port:
              number: 80
